export type User = {
  id: string;
  name: string;
  profileImage?: string;
};

export type Room = {
  id: string;
  name: string;
  passcode: string;
  imageUri?: string;
  leaderId: string;
  members: string[]; // User IDs
};

export type NoticeComment = {
  id: string;
  userId: string;
  text: string;
  createdAt: number;
};

export type Notice = {
  id: string;
  roomId: string;
  userId: string; // ID of the user who created the notice
  title: string;
  content: string;
  isPinned: boolean;
  imageUrls?: string[]; // Array of image URIs
  viewedBy: string[]; // User IDs who viewed the notice
  comments?: NoticeComment[];
  createdAt: number;
};

export type Comment = {
  id: string;
  userId: string;
  text: string;
  timestampMillis: number; // Video timestamp in ms
  createdAt: number;
};

export type VideoFeedback = {
  id: string;
  roomId: string;
  userId: string; // ID of the user who uploaded the video
  videoUrl: string; // uri or remote url
  title: string;
  comments: Comment[];
  createdAt: number;
};

export type PhotoComment = {
  id: string;
  userId: string;
  text: string;
  createdAt: number;
};

export type Photo = {
  id: string;
  roomId: string;
  userId: string; // ID of the user who uploaded the photo
  photoUrl: string;
  description?: string; // 💡 SNS형 텍스트
  comments?: PhotoComment[]; // 💡 사진 댓글
  createdAt: number;
};

export type ScheduleOption = {
  id: string;
  dateTime: string;
};

export type Schedule = {
  id: string;
  roomId: string;
  userId: string; // ID of the user who created the schedule
  title: string;
  options: ScheduleOption[];
  responses: { [userId: string]: string[] }; // userId to optionIds
  viewedBy: string[]; // User IDs who viewed the schedule
  startDate?: string;
  endDate?: string;
  sendNotification?: boolean;
  createdAt: number;
};

export type VoteOption = {
  id: string;
  text: string;
};

export type Vote = {
  id: string;
  roomId: string;
  userId: string; // ID of the user who created the vote
  question: string;
  options: VoteOption[];
  responses: { [userId: string]: string[] }; // userId to array of optionIds
  isAnonymous: boolean;
  allowMultiple: boolean;
  sendNotification: boolean;
  notificationMinutes?: number; // Minutes before deadline to notify
  deadline?: number; // Timestamp
  viewedBy: string[]; // User IDs who viewed the vote
  comments: Comment[];
  createdAt: number;
};

export type AlarmType = 'notice' | 'vote' | 'schedule' | 'general';

export type Alarm = {
  id: string;
  roomId: string;
  title: string;
  content: string;
  type: AlarmType;
  targetId: string; // noticeId, voteId, etc.
  createdAt: number;
  viewedBy: string[]; // User IDs who viewed the alarm
};

export type ThemeType = 'light' | 'dark' | 'pink' | 'shiba';

// --- Formation Management Types ---

export type Dancer = {
  id: string; // uuid generated by frontend
  name: string;
  color: string;
};

export type Position = {
  x: number;
  y: number;
};

export type Keyframe = {
  id: string; // uuid
  timestampMillis: number;
  positions: { [dancerId: string]: Position }; // dancerId -> {x, y}
};

export type FormationData = {
  dancers: Dancer[];
  keyframes: Keyframe[];
};

export type FormationSettings = {
  gridRows: number;
  gridCols: number;
  stageDirection: 'top' | 'bottom'; // "앞"이 위쪽인지 아래쪽인지
  snapToGrid: boolean;
};

export type Formation = {
  id: string;
  roomId: string;
  userId: string;
  title: string;
  audioUrl?: string; // supabase storage URL or external
  settings: FormationSettings;
  data: FormationData;
  createdAt: number;
};
